In [2]:
import pymongo

In [1]:
import pandas as pd

In [10]:
df = pd.read_parquet("/Users/yulin/workspace/extreme_quant/data/parquet/600000.SSE_DAILY.parquet")

In [11]:
df.head()

             Open  Close   High    Low      Volume       Amount trade_status
Date
2000-01-04  24.98  25.57  25.78  24.75   4496100.0  113946783.0           交易
2000-01-05  25.57  25.28  25.98  25.15   5252800.0  134465427.0           交易
2000-01-06  25.18  25.99  26.30  25.05   6229700.0  160059798.0           交易
2000-01-07  26.30  26.90  27.50  26.12  21355300.0  575751082.0           交易
2000-01-10  27.00  27.25  27.85  26.71  16539700.0  450453518.0           交易

In [7]:
df.trade_status.value_counts()

交易     5371
停牌      118
XD       15
DR        7
N         2
XR        1
待核查       0
Name: trade_status, dtype: int64

In [8]:
df=df[df["trade_status"]=="停牌"]

In [9]:
df.head()

             Open  Close   High    Low  Volume  Amount trade_status
Date
2000-05-08  25.00  25.00  25.00  25.00     0.0     0.0           停牌
2000-11-22  22.03  22.03  22.03  22.03     0.0     0.0           停牌
2001-05-28  20.25  20.25  20.25  20.25     0.0     0.0           停牌
2001-09-05  15.82  15.82  15.82  15.82     0.0     0.0           停牌
2002-02-04  14.14  14.14  14.14  14.14     0.0     0.0           停牌

In [14]:
df.loc["2000-04-25":"2000-05-15"]

             Open  Close   High    Low     Volume       Amount trade_status
Date
2000-04-25  24.81  24.84  25.09  24.78  2309500.0   57489169.0           交易
2000-04-26  24.88  25.00  25.57  24.80  3559400.0   89234644.0           交易
2000-04-27  25.00  24.74  25.20  24.68  3284200.0   81550296.0           交易
2000-04-28  24.74  25.00  25.00  24.65  3210800.0   79526614.0           交易
2000-05-08  25.00  25.00  25.00  25.00        0.0          0.0           停牌
2000-05-09  24.90  24.43  24.90  24.35  2606100.0   63808332.0           交易
2000-05-10  24.40  24.00  24.51  23.98  5873800.0  141397664.0           交易
2000-05-11  24.00  23.90  24.27  23.80  3388300.0   81370247.0           交易
2000-05-12  23.93  23.94  24.10  23.85  2969300.0   71131310.0           交易
2000-05-15  23.95  23.06  24.00  23.01  4078300.0   94939549.0           交易

In [ ]:
""