In [2]:
import pymongo

In [1]:
import pandas as pd

In [10]:
df = pd.read_parquet("/Users/yulin/workspace/extreme_quant/data/parquet/600000.SSE_DAILY.parquet")

In [11]:
df.head()

             Open  Close   High    Low      Volume       Amount trade_status
Date
2000-01-04  24.98  25.57  25.78  24.75   4496100.0  113946783.0           交易
2000-01-05  25.57  25.28  25.98  25.15   5252800.0  134465427.0           交易
2000-01-06  25.18  25.99  26.30  25.05   6229700.0  160059798.0           交易
2000-01-07  26.30  26.90  27.50  26.12  21355300.0  575751082.0           交易
2000-01-10  27.00  27.25  27.85  26.71  16539700.0  450453518.0           交易

In [7]:
df.trade_status.value_counts()

交易     5371
停牌      118
XD       15
DR        7
N         2
XR        1
待核查       0
Name: trade_status, dtype: int64

In [8]:
df=df[df["trade_status"]=="停牌"]

In [9]:
df.head()

             Open  Close   High    Low  Volume  Amount trade_status
Date
2000-05-08  25.00  25.00  25.00  25.00     0.0     0.0           停牌
2000-11-22  22.03  22.03  22.03  22.03     0.0     0.0           停牌
2001-05-28  20.25  20.25  20.25  20.25     0.0     0.0           停牌
2001-09-05  15.82  15.82  15.82  15.82     0.0     0.0           停牌
2002-02-04  14.14  14.14  14.14  14.14     0.0     0.0           停牌

In [14]:
df.loc["2000-04-25":"2000-05-15"]

             Open  Close   High    Low     Volume       Amount trade_status
Date
2000-04-25  24.81  24.84  25.09  24.78  2309500.0   57489169.0           交易
2000-04-26  24.88  25.00  25.57  24.80  3559400.0   89234644.0           交易
2000-04-27  25.00  24.74  25.20  24.68  3284200.0   81550296.0           交易
2000-04-28  24.74  25.00  25.00  24.65  3210800.0   79526614.0           交易
2000-05-08  25.00  25.00  25.00  25.00        0.0          0.0           停牌
2000-05-09  24.90  24.43  24.90  24.35  2606100.0   63808332.0           交易
2000-05-10  24.40  24.00  24.51  23.98  5873800.0  141397664.0           交易
2000-05-11  24.00  23.90  24.27  23.80  3388300.0   81370247.0           交易
2000-05-12  23.93  23.94  24.10  23.85  2969300.0   71131310.0           交易
2000-05-15  23.95  23.06  24.00  23.01  4078300.0   94939549.0           交易

In [26]:
import tushare as ts
ts.set_token("b9d8623c7dbde160e75147e2b47588810dd8dc3033ec8cadc9f64f53")
pro = ts.pro_api()
df = pro.trade_cal(exchange='SZSE', start_date='1989', end_date='2030')

In [27]:
df.exchange.value_counts()

SZSE    11505
Name: exchange, dtype: int64

In [28]:
df.tail()

      exchange  cal_date  is_open pretrade_date
11500     SZSE  20221227        1      20221226
11501     SZSE  20221228        1      20221227
11502     SZSE  20221229        1      20221228
11503     SZSE  20221230        1      20221229
11504     SZSE  20221231        0      20221230

In [29]:
df.head()

  exchange  cal_date  is_open pretrade_date
0     SZSE  19910703        1          None
1     SZSE  19910704        1      19910703
2     SZSE  19910705        1      19910704
3     SZSE  19910706        0      19910705
4     SZSE  19910707        0      19910705

In [30]:
from enum import Enum
class Exchange(Enum):
    SSE = 0         # 上交所
    SZSE = 1        # 深交所
    CFFEX = 2       # 中金所
    SHFE = 3        # 上期所
    CZCE = 4        # 郑商所
    DCE = 5         # 大商所
    INE = 6         # 上能源

In [32]:
Exchange.SSE.name

'SSE'

In [1]:
import tushare as ts

ts.set_token("b9d8623c7dbde160e75147e2b47588810dd8dc3033ec8cadc9f64f53")
PRO = ts.pro_api()

In [114]:
df_symbol = PRO.stock_basic(exchange="SSE", list_status='L', fields='ts_code,symbol,name,area,industry,list_date,list_status,fullname,exchange,market,is_hs,curr_type')

In [59]:
df_symbol.set_index("ts_code", inplace=True)

In [117]:
for x in df_symbol.ts_code:
    print(x) 
    break

600000.SH

In [58]:
df_symbol.index[0]

0

In [41]:
df = PRO.trade_cal(exchange="SZSE,SSE", start_date='1989', end_date='2030')

In [42]:
df.head()

Empty DataFrame
Columns: [exchange, cal_date, is_open, pretrade_date]
Index: []

In [36]:
df.exchange.value_counts()

SZSE    11505
Name: exchange, dtype: int64

In [62]:
df = PRO.query("daily", ts_code="600602.SH", start_date="19900101",
                   end_date="20300101")

In [63]:
from data.tushare_api import *

In [118]:
df1 = get_symbol_hist("600602.SH", start_date="20191201", end_date="20191210")

In [93]:
df1

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,600602.SH,20191210,8.14,8.22,8.10,8.19,8.16,0.03,0.3676,61111.63,49869.217
1,600602.SH,20191209,8.09,8.19,8.04,8.16,8.06,0.10,1.2407,68311.12,55465.699
2,600602.SH,20191206,8.07,8.11,8.00,8.06,8.11,-0.05,-0.6165,52099.91,41926.983
3,600602.SH,20191205,8.05,8.15,7.99,8.11,8.03,0.08,0.9963,81254.77,65569.553
4,600602.SH,20191204,8.03,8.14,7.97,8.03,8.08,-0.05,-0.6188,52009.90,41914.993
5,600602.SH,20191203,7.92,8.10,7.87,8.08,7.88,0.20,2.5381,58209.52,46490.771
6,600602.SH,20191202,7.91,8.01,7.85,7.88,7.97,-0.09,-1.1292,40127.22,31745.080

In [148]:
df2 = get_symbol_hist("600651.SH", start_date="19800101", end_date="")

In [149]:
df2

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount
0,600651.SH,20221212,3.42,3.42,3.35,3.37,3.41,-0.04,-1.1730,75945.00,25686.307
1,600651.SH,20221209,3.44,3.46,3.40,3.41,3.44,-0.03,-0.8721,75448.00,25811.749
2,600651.SH,20221208,3.46,3.47,3.43,3.44,3.47,-0.03,-0.8646,56654.64,19515.878
3,600651.SH,20221207,3.50,3.51,3.44,3.47,3.50,-0.03,-0.8571,73822.74,25563.307
4,600651.SH,20221206,3.51,3.53,3.47,3.50,3.49,0.01,0.2865,84360.45,29492.597
...,...,...,...,...,...,...,...,...,...,...,...
5995,600651.SH,19970717,9.50,9.78,9.30,9.50,9.43,0.07,0.7400,4092.00,3911.263
5996,600651.SH,19970716,9.68,9.70,9.35,9.43,9.70,-0.27,-2.7800,6052.00,5742.906
5997,600651.SH,19970715,9.77,9.90,9.40,9.70,9.90,-0.20,-2.0200,5489.00,5310.651
5998,600651.SH,19970714,9.60,9.99,9.38,9.90,9.58,0.32,3.3400,7594.00,7394.797
5999,600651.SH,19970711,9.10,9.60,9.10,9.58,9.17,0.41,4.4700,5583.00,5251.604

In [121]:
df1.set_index("trade_date", inplace=True)
df2.set_index("trade_date", inplace=True)
df1.index = pd.to_datetime(df1.index)
df2.index = pd.to_datetime(df2.index)

In [122]:
df1

,ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount
trade_date,,,,,,,,,,
2019-12-10,600602.SH,8.14,8.22,8.10,8.19,8.16,0.03,0.3676,61111.63,49869.217
2019-12-09,600602.SH,8.09,8.19,8.04,8.16,8.06,0.10,1.2407,68311.12,55465.699
2019-12-06,600602.SH,8.07,8.11,8.00,8.06,8.11,-0.05,-0.6165,52099.91,41926.983
2019-12-05,600602.SH,8.05,8.15,7.99,8.11,8.03,0.08,0.9963,81254.77,65569.553
2019-12-04,600602.SH,8.03,8.14,7.97,8.03,8.08,-0.05,-0.6188,52009.90,41914.993
2019-12-03,600602.SH,7.92,8.10,7.87,8.08,7.88,0.20,2.5381,58209.52,46490.771
2019-12-02,600602.SH,7.91,8.01,7.85,7.88,7.97,-0.09,-1.1292,40127.22,31745.080

In [131]:
df3=pd.concat([df1, df2], axis=0)

In [132]:
df3 = df3[~df3.index.duplicated(keep='first')]

In [133]:
df3

,ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount
trade_date,,,,,,,,,,
2019-12-10,600602.SH,8.14,8.22,8.10,8.19,8.16,0.03,0.3676,61111.63,49869.217
2019-12-09,600602.SH,8.09,8.19,8.04,8.16,8.06,0.10,1.2407,68311.12,55465.699
2019-12-06,600602.SH,8.07,8.11,8.00,8.06,8.11,-0.05,-0.6165,52099.91,41926.983
2019-12-05,600602.SH,8.05,8.15,7.99,8.11,8.03,0.08,0.9963,81254.77,65569.553
2019-12-04,600602.SH,8.03,8.14,7.97,8.03,8.08,-0.05,-0.6188,52009.90,41914.993
2019-12-03,600602.SH,7.92,8.10,7.87,8.08,7.88,0.20,2.5381,58209.52,46490.771
2019-12-02,600602.SH,7.91,8.01,7.85,7.88,7.97,-0.09,-1.1292,40127.22,31745.080
2019-12-20,600602.SH,8.39,8.43,8.24,8.37,8.40,-0.03,-0.3571,95244.13,79336.613
2019-12-19,600602.SH,8.40,8.48,8.32,8.40,8.41,-0.01,-0.1189,91483.98,76760.001
2019-12-18,600602.SH,8.44,8.53,8.34,8.41,8.42,-0.01,-0.1188,116722.06,98173.628
2019-12-17,600602.SH,8.35,8.47,8.31,8.42,8.30,0.12,1.4458,137504.13,115454.344
2019-12-16,600602.SH,8.05,8.35,7.99,8.30,8.05,0.25,3.1056,148648.97,121642.081
2019-12-13,600602.SH,8.05,8.08,7.93,8.05,8.05,0.00,0.0000,94883.19,76068.546
2019-12-12,600602.SH,8.04,8.06,7.89,8.05,8.04,0.01,0.1244,88665.12,70615.546
2019-12-11,600602.SH,8.20,8.20,7.99,8.04,8.19,-0.15,-1.8315,81336.39,65534.671

In [135]:
df3.sort_index(inplace=True)

In [136]:
df3

,ts_code,open,high,low,close,pre_close,change,pct_chg,vol,amount
trade_date,,,,,,,,,,
2019-12-02,600602.SH,7.91,8.01,7.85,7.88,7.97,-0.09,-1.1292,40127.22,31745.080
2019-12-03,600602.SH,7.92,8.10,7.87,8.08,7.88,0.20,2.5381,58209.52,46490.771
2019-12-04,600602.SH,8.03,8.14,7.97,8.03,8.08,-0.05,-0.6188,52009.90,41914.993
2019-12-05,600602.SH,8.05,8.15,7.99,8.11,8.03,0.08,0.9963,81254.77,65569.553
2019-12-06,600602.SH,8.07,8.11,8.00,8.06,8.11,-0.05,-0.6165,52099.91,41926.983
2019-12-09,600602.SH,8.09,8.19,8.04,8.16,8.06,0.10,1.2407,68311.12,55465.699
2019-12-10,600602.SH,8.14,8.22,8.10,8.19,8.16,0.03,0.3676,61111.63,49869.217
2019-12-11,600602.SH,8.20,8.20,7.99,8.04,8.19,-0.15,-1.8315,81336.39,65534.671
2019-12-12,600602.SH,8.04,8.06,7.89,8.05,8.04,0.01,0.1244,88665.12,70615.546
2019-12-13,600602.SH,8.05,8.08,7.93,8.05,8.05,0.00,0.0000,94883.19,76068.546
2019-12-16,600602.SH,8.05,8.35,7.99,8.30,8.05,0.25,3.1056,148648.97,121642.081
2019-12-17,600602.SH,8.35,8.47,8.31,8.42,8.30,0.12,1.4458,137504.13,115454.344
2019-12-18,600602.SH,8.44,8.53,8.34,8.41,8.42,-0.01,-0.1188,116722.06,98173.628
2019-12-19,600602.SH,8.40,8.48,8.32,8.40,8.41,-0.01,-0.1189,91483.98,76760.001
2019-12-20,600602.SH,8.39,8.43,8.24,8.37,8.40,-0.03,-0.3571,95244.13,79336.613

In [137]:
df = pd.read_csv("/Users/yulin/workspace/extreme_quant/dataset/stock_sse/history/600000.SH.csv")

In [141]:
df.set_index("trade_date", inplace=True)

In [144]:
df.index = pd.to_datetime(df.index)

In [145]:
df.index

DatetimeIndex(['2000-01-04', '2000-01-05', '2000-01-06', '2000-01-07',
               '2000-01-10', '2000-01-11', '2000-01-12', '2000-01-13',
               '2000-01-14', '2000-01-17',
               ...
               '2022-11-29', '2022-11-30', '2022-12-01', '2022-12-02',
               '2022-12-05', '2022-12-06', '2022-12-07', '2022-12-08',
               '2022-12-09', '2022-12-12'],
              dtype='datetime64[ns]', name='trade_date', length=5442, freq=None)