In [2]:
import pymongo

In [1]:
import pandas as pd

In [10]:
df = pd.read_parquet("/Users/yulin/workspace/extreme_quant/data/parquet/600000.SSE_DAILY.parquet")

In [11]:
df.head()

             Open  Close   High    Low      Volume       Amount trade_status
Date
2000-01-04  24.98  25.57  25.78  24.75   4496100.0  113946783.0           交易
2000-01-05  25.57  25.28  25.98  25.15   5252800.0  134465427.0           交易
2000-01-06  25.18  25.99  26.30  25.05   6229700.0  160059798.0           交易
2000-01-07  26.30  26.90  27.50  26.12  21355300.0  575751082.0           交易
2000-01-10  27.00  27.25  27.85  26.71  16539700.0  450453518.0           交易

In [7]:
df.trade_status.value_counts()

交易     5371
停牌      118
XD       15
DR        7
N         2
XR        1
待核查       0
Name: trade_status, dtype: int64

In [8]:
df=df[df["trade_status"]=="停牌"]

In [9]:
df.head()

             Open  Close   High    Low  Volume  Amount trade_status
Date
2000-05-08  25.00  25.00  25.00  25.00     0.0     0.0           停牌
2000-11-22  22.03  22.03  22.03  22.03     0.0     0.0           停牌
2001-05-28  20.25  20.25  20.25  20.25     0.0     0.0           停牌
2001-09-05  15.82  15.82  15.82  15.82     0.0     0.0           停牌
2002-02-04  14.14  14.14  14.14  14.14     0.0     0.0           停牌

In [14]:
df.loc["2000-04-25":"2000-05-15"]

             Open  Close   High    Low     Volume       Amount trade_status
Date
2000-04-25  24.81  24.84  25.09  24.78  2309500.0   57489169.0           交易
2000-04-26  24.88  25.00  25.57  24.80  3559400.0   89234644.0           交易
2000-04-27  25.00  24.74  25.20  24.68  3284200.0   81550296.0           交易
2000-04-28  24.74  25.00  25.00  24.65  3210800.0   79526614.0           交易
2000-05-08  25.00  25.00  25.00  25.00        0.0          0.0           停牌
2000-05-09  24.90  24.43  24.90  24.35  2606100.0   63808332.0           交易
2000-05-10  24.40  24.00  24.51  23.98  5873800.0  141397664.0           交易
2000-05-11  24.00  23.90  24.27  23.80  3388300.0   81370247.0           交易
2000-05-12  23.93  23.94  24.10  23.85  2969300.0   71131310.0           交易
2000-05-15  23.95  23.06  24.00  23.01  4078300.0   94939549.0           交易

In [26]:
import tushare as ts
ts.set_token("b9d8623c7dbde160e75147e2b47588810dd8dc3033ec8cadc9f64f53")
pro = ts.pro_api()
df = pro.trade_cal(exchange='SZSE', start_date='1989', end_date='2030')

In [27]:
df.exchange.value_counts()

SZSE    11505
Name: exchange, dtype: int64

In [28]:
df.tail()

      exchange  cal_date  is_open pretrade_date
11500     SZSE  20221227        1      20221226
11501     SZSE  20221228        1      20221227
11502     SZSE  20221229        1      20221228
11503     SZSE  20221230        1      20221229
11504     SZSE  20221231        0      20221230

In [29]:
df.head()

  exchange  cal_date  is_open pretrade_date
0     SZSE  19910703        1          None
1     SZSE  19910704        1      19910703
2     SZSE  19910705        1      19910704
3     SZSE  19910706        0      19910705
4     SZSE  19910707        0      19910705

In [30]:
from enum import Enum
class Exchange(Enum):
    SSE = 0         # 上交所
    SZSE = 1        # 深交所
    CFFEX = 2       # 中金所
    SHFE = 3        # 上期所
    CZCE = 4        # 郑商所
    DCE = 5         # 大商所
    INE = 6         # 上能源

In [32]:
Exchange.SSE.name

'SSE'

In [1]:
import tushare as ts

ts.set_token("b9d8623c7dbde160e75147e2b47588810dd8dc3033ec8cadc9f64f53")
PRO = ts.pro_api()

In [48]:
df_symbol = PRO.stock_basic(exchange="SSE", list_status='L', fields='ts_code,symbol,name,area,industry,list_date,list_status,fullname,exchange,market,is_hs,curr_type')

In [59]:
df_symbol.set_index("ts_code", inplace=True)

In [61]:
for x in df_symbol.index:
    print(df_symbol[x]) 
    break

KeyError: '600000.SH'

In [58]:
df_symbol.index[0]

0

In [41]:
df = PRO.trade_cal(exchange="SZSE,SSE", start_date='1989', end_date='2030')

In [42]:
df.head()

Empty DataFrame
Columns: [exchange, cal_date, is_open, pretrade_date]
Index: []

In [36]:
df.exchange.value_counts()

SZSE    11505
Name: exchange, dtype: int64

In [45]:
df = PRO.query("daily", ts_code="600000.SH", start_date="19900101",
                   end_date="20300101")